# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05d9fbbe481584742e4b5ede3801aa3a0613281d3eb6c6ad28ff492825eb70f023c44ef2114b7b77bae878f169e3abd3007c1ed9e54fcfe5512acd91fdfecff9

test:
  secret_key_base: 160e9a631a48999a8b918b14c19f4e264113d8fa3f3bc7c546daaa1db29816398cea51d34129b5bbb7fff80a8f7a6d7de4779080bf39231d11b574332eea77eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
